# Generated by Django 5.0.6 on 2024-05-15 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='comment_ck',
            field=models.BooleanField(default=True),
        ),
    ]
