# Generated by Django 5.0.4 on 2024-04-23 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='referrer',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
