# Generated by Django 5.0.4 on 2024-04-25 09:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hashtags", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hashtag",
            name="hashtag",
            field=models.CharField(max_length=50),
        ),
    ]
