# Generated by Django 5.0.4 on 2024-04-30 04:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hashtags", "0002_alter_hashtag_hashtag"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="hashtag",
            table="hashtags",
        ),
    ]
