# Generated by Django 5.0.6 on 2024-05-17 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comments", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="paraent_comment",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="comments.comment",
            ),
        ),
    ]
