# Generated by Django 5.0.6 on 2024-05-18 16:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comments", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="likes",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
