# Generated by Django 5.0.6 on 2024-05-17 16:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("comments", "0004_comment_paraent_comment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="paraent_comment",
            new_name="recomment",
        ),
    ]
