# Generated by Django 5.0.6 on 2024-05-18 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0003_initial'),
        ('posts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='archive',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='archived_in', to='posts.post'),
        ),
    ]
