# Generated by Django 5.0.6 on 2024-05-18 06:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0006_alter_archivestatus_user'),
        ('posts', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archive',
            name='post',
        ),
        migrations.AddField(
            model_name='archive',
            name='posts',
            field=models.ManyToManyField(blank=True, related_name='archives', to='posts.post'),
        ),
        migrations.AlterField(
            model_name='archivestatus',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='archive_status', to=settings.AUTH_USER_MODEL),
        ),
    ]
