# Generated by Django 5.0.6 on 2024-05-18 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0007_remove_archive_post_archive_posts_and_more'),
        ('posts', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archive',
            name='posts',
        ),
        migrations.CreateModel(
            name='ArchivePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archive_posts', to='archive.archive')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archive_posts', to='posts.post')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
